# Generated by Django 3.0.2 on 2020-01-11 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('action', models.IntegerField()),
                ('adventure', models.IntegerField()),
                ('anthology', models.IntegerField()),
                ('biographical', models.IntegerField()),
                ('biopic', models.IntegerField()),
                ('campus', models.IntegerField()),
                ('children', models.IntegerField()),
                ('comedy', models.IntegerField()),
                ('crime', models.IntegerField()),
                ('drama', models.IntegerField()),
                ('family', models.IntegerField()),
                ('fantasy', models.IntegerField()),
                ('fiction', models.IntegerField()),
                ('heist', models.IntegerField()),
                ('historical', models.IntegerField()),
                ('horror', models.IntegerField()),
                ('masala', models.IntegerField()),
                ('music', models.IntegerField()),
                ('mystery', models.IntegerField()),
                ('patriotism', models.IntegerField()),
                ('period', models.IntegerField()),
                ('political', models.IntegerField()),
                ('psychological', models.IntegerField()),
                ('revenge', models.IntegerField()),
                ('road', models.IntegerField()),
                ('romantic', models.IntegerField()),
                ('satire', models.IntegerField()),
                ('social', models.IntegerField()),
                ('sport', models.IntegerField()),
                ('suspense', models.IntegerField()),
                ('thriller', models.IntegerField()),
                ('malayalam', models.IntegerField()),
                ('tamil', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
